[workspace]
members = [
  "solana/consts",
  "solana/utils",
  "solana/vaas",
  "universal/io",
  "universal/raw-vaas",
]
resolver = "2"

[workspace.package]
version = "0.0.0"
edition = "2021"
authors = ["Wormhole Contributors"]
license = "Apache-2.0"
homepage = "https://github.com/wormhole-foundation/wormhole-sdk-rs"
repository = "https://github.com/wormhole-foundation/wormhole-sdk-rs"
rust-version = "1.75"

[workspace.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[workspace.dependencies]
hex-literal = "1.0.0"
cfg-if = "1.0"
ruint = { version = "1.9.0", default-features = false }
ruint-macro = "1.1.0"

### Solana related
solana-program = "2"
borsh = "1.5.7"
anchor-lang = "0.31.1"

serde = "1.0"
serde_json = "1.0"

wormhole-io = { path = "universal/io", version = "0.0.0" }
wormhole-raw-vaas = { path = "universal/raw-vaas", version = "0.0.0" }
wormhole-solana-consts = { path = "solana/consts", version = "0.0.0" }
